tap "borkdude/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "bitwarden-cli"
brew "fzf"
brew "git"
brew "git-delta"
brew "grep"
brew "jq"
brew "starship"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "wget"
brew "lsd"

cask "bitwarden"
cask "raycast"
cask "visual-studio-code"
cask "hyper"
cask "deepl"
cask "karabiner-elements"
cask "google-chrome"
cask "app-cleaner"
cask "authy"

cask "font-hack-nerd-font"
