modmap:
  - name: SandS
    remap:
      Space: [Shift_L, Space]
  - name: Caps to Ctrl
    remap:
      CapsLock: LEFTCTRL
  - name: Shift And Alt
    remap:
      Shift_L: [ALT_L, Shift_L]
keymap:
  - name: Vim binding
    remap:
      M-h: left
      M-j: down
      M-k: up
      M-l: right
  - name: Mac Emacs binding
    remap:
      M-a: Home
      M-e: End