modmap:
  - name: SandS
    remap:
      Space: [Shift_L, Space]
  - name: simple remap
    remap:
      CapsLock: LEFTCTRL
      # Alt_R: SUPER_L
  - name: Shift And Alt
    remap:
      Shift_L: [ALT_L, Shift_L]
keymap:
  - name: Vim binding
    remap:
      M-h: left
      M-j: down
      M-k: up
      M-l: right
  - name: Mac Emacs binding
    remap:
      M-a: Home
      M-e: End
  - name: Term Copy and Paste
    remap:
      M-c: C-c
      M-v: C-v
    application:
      not: [gnome-terminal-server]

